% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Assignment 1},
  pdfauthor={Group 6},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Assignment 1}
\author{Group 6}
\date{9/10/2020}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(e1071)}
\NormalTok{rice <-}\StringTok{ }\KeywordTok{read.delim}\NormalTok{(}\StringTok{"RiceDataset.txt"}\NormalTok{, }\DataTypeTok{header =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{stringsAsFactors =} \OtherTok{TRUE}\NormalTok{)}

\NormalTok{index <-}\StringTok{ }\DecValTok{1}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(rice)}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{testindex <-}\StringTok{ }\KeywordTok{sample}\NormalTok{(index, }\KeywordTok{trunc}\NormalTok{(}\KeywordTok{length}\NormalTok{(index)}\OperatorTok{/}\DecValTok{3}\NormalTok{)) }
\NormalTok{testset <-}\StringTok{ }\NormalTok{rice[testindex,]}
\NormalTok{trainset <-}\StringTok{ }\NormalTok{rice[}\OperatorTok{-}\NormalTok{testindex,]}
\NormalTok{svm.model <-}\StringTok{ }\KeywordTok{svm}\NormalTok{(CLASS }\OperatorTok{~}\StringTok{ }\NormalTok{., }\DataTypeTok{data=}\NormalTok{trainset, }\DataTypeTok{type=}\StringTok{"C-classification"}\NormalTok{, }\DataTypeTok{kernel=}\StringTok{"linear"}\NormalTok{)}

\NormalTok{results_train <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(svm.model,trainset[,}\OperatorTok{-}\DecValTok{8}\NormalTok{])}
\NormalTok{results_test <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(svm.model, testset[,}\OperatorTok{-}\DecValTok{8}\NormalTok{] )}
\NormalTok{cf.train <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{table}\NormalTok{(}\DataTypeTok{pred=}\NormalTok{results_train,}\DataTypeTok{actual=}\NormalTok{trainset}\OperatorTok{$}\NormalTok{CLASS)) }
\NormalTok{cf.test <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{table}\NormalTok{(}\DataTypeTok{pred=}\NormalTok{results_test,}\DataTypeTok{actual=}\NormalTok{testset}\OperatorTok{$}\NormalTok{CLASS))}
\NormalTok{trainAccuracy =}\StringTok{ }\NormalTok{(cf.train)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.train)}
\NormalTok{cf.test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           actual
## pred       Cammeo Osmancik
##   Cammeo      488       42
##   Osmancik     51      689
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accuracy_train =}\StringTok{ }\NormalTok{(cf.train[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\NormalTok{cf.train[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.train)}
\NormalTok{accuracy_test =}\StringTok{ }\NormalTok{(cf.test[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\NormalTok{cf.test[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.test)}
\NormalTok{accuracy_train}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.930315
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accuracy_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9267717
\end{verbatim}

\hypertarget{interpretation-of-r-code}{%
\section{Interpretation of R code}\label{interpretation-of-r-code}}

\hypertarget{accuracy-of-r-code}{%
\section{Accuracy of R code}\label{accuracy-of-r-code}}

\textbf{Accuracy over on training set:} 93.03\% \textbf{Accuracy over
test set:} 92.68\%

\hypertarget{using-other-kernels}{%
\section{Using other kernels}\label{using-other-kernels}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{svm.model <-}\StringTok{ }\KeywordTok{svm}\NormalTok{(CLASS }\OperatorTok{~}\StringTok{ }\NormalTok{., }\DataTypeTok{data=}\NormalTok{trainset, }\DataTypeTok{type=}\StringTok{"C-classification"}\NormalTok{, }\DataTypeTok{kernel=}\StringTok{"polynomial"}\NormalTok{)}

\NormalTok{results_train <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(svm.model,trainset[,}\OperatorTok{-}\DecValTok{8}\NormalTok{])}
\NormalTok{results_test <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(svm.model, testset[,}\OperatorTok{-}\DecValTok{8}\NormalTok{] )}
\NormalTok{cf.train <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{table}\NormalTok{(}\DataTypeTok{pred=}\NormalTok{results_train,}\DataTypeTok{actual=}\NormalTok{trainset}\OperatorTok{$}\NormalTok{CLASS)) }
\NormalTok{cf.test <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{table}\NormalTok{(}\DataTypeTok{pred=}\NormalTok{results_test,}\DataTypeTok{actual=}\NormalTok{testset}\OperatorTok{$}\NormalTok{CLASS))}
\NormalTok{trainAccuracy =}\StringTok{ }\NormalTok{(cf.train)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.train)}
\NormalTok{cf.test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           actual
## pred       Cammeo Osmancik
##   Cammeo      435       21
##   Osmancik    104      710
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accuracy_train =}\StringTok{ }\NormalTok{(cf.train[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\NormalTok{cf.train[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.train)}
\NormalTok{accuracy_test =}\StringTok{ }\NormalTok{(cf.test[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\NormalTok{cf.test[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.test)}
\NormalTok{accuracy_train}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9106299
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accuracy_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9015748
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{svm.model <-}\StringTok{ }\KeywordTok{svm}\NormalTok{(CLASS }\OperatorTok{~}\StringTok{ }\NormalTok{., }\DataTypeTok{data=}\NormalTok{trainset, }\DataTypeTok{type=}\StringTok{"C-classification"}\NormalTok{, }\DataTypeTok{kernel=}\StringTok{"sigmoid"}\NormalTok{)}

\NormalTok{results_train <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(svm.model,trainset[,}\OperatorTok{-}\DecValTok{8}\NormalTok{])}
\NormalTok{results_test <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(svm.model, testset[,}\OperatorTok{-}\DecValTok{8}\NormalTok{] )}
\NormalTok{cf.train <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{table}\NormalTok{(}\DataTypeTok{pred=}\NormalTok{results_train,}\DataTypeTok{actual=}\NormalTok{trainset}\OperatorTok{$}\NormalTok{CLASS)) }
\NormalTok{cf.test <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{table}\NormalTok{(}\DataTypeTok{pred=}\NormalTok{results_test,}\DataTypeTok{actual=}\NormalTok{testset}\OperatorTok{$}\NormalTok{CLASS))}
\NormalTok{trainAccuracy =}\StringTok{ }\NormalTok{(cf.train)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.train)}
\NormalTok{cf.test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           actual
## pred       Cammeo Osmancik
##   Cammeo      458       88
##   Osmancik     81      643
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accuracy_train =}\StringTok{ }\NormalTok{(cf.train[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\NormalTok{cf.train[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.train)}
\NormalTok{accuracy_test =}\StringTok{ }\NormalTok{(cf.test[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\NormalTok{cf.test[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.test)}
\NormalTok{accuracy_train}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8712598
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accuracy_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8669291
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{svm.model <-}\StringTok{ }\KeywordTok{svm}\NormalTok{(CLASS }\OperatorTok{~}\StringTok{ }\NormalTok{., }\DataTypeTok{data=}\NormalTok{trainset, }\DataTypeTok{type=}\StringTok{"C-classification"}\NormalTok{, }\DataTypeTok{kernel=}\StringTok{"radial"}\NormalTok{)}

\NormalTok{results_train <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(svm.model,trainset[,}\OperatorTok{-}\DecValTok{8}\NormalTok{])}
\NormalTok{results_test <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(svm.model, testset[,}\OperatorTok{-}\DecValTok{8}\NormalTok{] )}
\NormalTok{cf.train <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{table}\NormalTok{(}\DataTypeTok{pred=}\NormalTok{results_train,}\DataTypeTok{actual=}\NormalTok{trainset}\OperatorTok{$}\NormalTok{CLASS)) }
\NormalTok{cf.test <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{table}\NormalTok{(}\DataTypeTok{pred=}\NormalTok{results_test,}\DataTypeTok{actual=}\NormalTok{testset}\OperatorTok{$}\NormalTok{CLASS))}
\NormalTok{trainAccuracy =}\StringTok{ }\NormalTok{(cf.train)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.train)}
\NormalTok{cf.test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           actual
## pred       Cammeo Osmancik
##   Cammeo      483       41
##   Osmancik     56      690
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accuracy_train =}\StringTok{ }\NormalTok{(cf.train[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\NormalTok{cf.train[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.train)}
\NormalTok{accuracy_test =}\StringTok{ }\NormalTok{(cf.test[}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{] }\OperatorTok{+}\StringTok{ }\NormalTok{cf.test[}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{])}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(cf.test)}
\NormalTok{accuracy_train}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9338583
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{accuracy_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.923622
\end{verbatim}

\hypertarget{summary}{%
\subsection{Summary}\label{summary}}

\hypertarget{accuracy-on-test-set-of-different-kernels}{%
\subsubsection{Accuracy on test set of different
kernels:}\label{accuracy-on-test-set-of-different-kernels}}

\begin{itemize}
\tightlist
\item
  Linear: 92.68\%
\item
  Polynomial: 90.16\%
\item
  Sigmoid: 86.69\%
\item
  Radial basis: 92.36\% \#\#\# Explanations:
\end{itemize}

\end{document}
